#SPDX-License-Identifier: MIT-0
# tasks file for docker
---
- name: Installeer benodigde pakketten voor Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
 
- name: Voeg docker GPG-sleutel toe
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
 
- name: Voeg Docker repository toe aan APT
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
 
- name: Installeer Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  notify: Restart Docker service

- name: Zorg dat Docker draait
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: Wacht op 'docker.sock' om beschikbaar te zijn
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 30
 
- name: Voeg de gebruiker 'testuser' toe aan de docker-groep zodat deze gebruiker docker-opdrachten kan uitvoeren zonder sudo
  user:
    name: testuser
    groups: docker
    append: yes

- name: Start een 'Hello World' container
  community.docker.docker_container:
    name: hello-web
    image: nginx:alpine
    state: started
    restart_policy: always
    ports:
      - "80:80"
# tasks file for IAC_docker